//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@interface _NCCardViewControllerView : NSVisualEffectView
{
    BOOL _forceDarkCompatibleLook;
    BOOL _darkLook;
    unsigned long long _cardMaterial;
}

@property(readonly) unsigned long long cardMaterial; // @synthesize cardMaterial=_cardMaterial;
- (void)updateLayer;
- (void)_setupAppearance:(_Bool)arg1;
- (id)initWithCardMaterial:(unsigned long long)arg1;

@end

