//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@class CALayer;

@interface _NCReplyScrollView : NSScrollView
{
    CALayer *_imageLayer;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)contentSize;
- (void)_updateLayerMasksToBoundsFromView;
- (BOOL)clipsToBounds;
- (void)layout;
- (void)awakeFromNib;

@end

