//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

@interface _NCTodayListClipView : NSClipView
{
    double _hiddenScrollHeight;
}

@property(nonatomic) double hiddenScrollHeight; // @synthesize hiddenScrollHeight=_hiddenScrollHeight;
- (struct CGRect)documentRect;

@end

