//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@interface _NCTodayListScrollView : NSScrollView
{
    id __owner;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id _owner; // @synthesize _owner=__owner;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

