//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class _NCWindow;

@protocol _NCWindowDelegate
- (void)ncWindow:(_NCWindow *)arg1 firstResponderChangedFrom:(id)arg2 to:(id)arg3;
@end

