//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

@class MISSING_TYPE;

@interface _NotificationTableClipView : NSClipView
{
    MISSING_TYPE *hiddenScrollHeight;
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGRect documentRect;

@end

