//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp19NotificationTrigger.h"

@interface _TtC21NotificationCenterApp25NotificationLegacyTrigger : _TtC21NotificationCenterApp19NotificationTrigger
{
}

@end

