//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp15AlertScrollView.h"

#import "NCMaterialDelegate-Protocol.h"

@interface _TtC21NotificationCenterApp15AlertScrollView (NotificationCenterApp) <NCMaterialDelegate>
- (void)appearanceChanged:(BOOL)arg1;
- (void)materialChanged:(unsigned char)arg1;
@end

