//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NCCARemoteSession, NCNotificationWindow, NSDate, NSImage, _TtC21NotificationCenterApp25NotificationSummaryBanner, _TtC21NotificationCenterApp7AppInfo;
@protocol _TtP21NotificationCenterApp14BannerDelegate_;

@interface _TtC21NotificationCenterApp12RemoteBanner : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *app;
    MISSING_TYPE *session;
    MISSING_TYPE *window;
    MISSING_TYPE *displayTime;
    MISSING_TYPE *dismissTime;
    MISSING_TYPE *displayedFirstAtLockscreen;
    MISSING_TYPE *pendingInitialDisplay;
    MISSING_TYPE *registeredTalkingAlerts;
    MISSING_TYPE *dismissed;
    MISSING_TYPE *creationOrder;
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)dismissTimeWithLessThan:(double)arg1;
- (void)swapWith:(id)arg1;
- (void)clearWindow;
- (id)windowCreateIfNecessary;
@property(nonatomic, readonly) NSImage *identityImage;
@property(nonatomic, readonly) _TtC21NotificationCenterApp25NotificationSummaryBanner *asSummaryModel;
@property(nonatomic, readonly) BOOL isSummaryModel;
@property(nonatomic, readonly) NSDate *deliveredDate;
@property(nonatomic) long long creationOrder; // @synthesize creationOrder;
@property(nonatomic) BOOL dismissed; // @synthesize dismissed;
@property(nonatomic, readonly) NSImage *identityBadgingImage;
@property(nonatomic, readonly) BOOL isRemote;
@property(nonatomic) BOOL registeredTalkingAlerts; // @synthesize registeredTalkingAlerts;
@property(nonatomic, readonly) BOOL showOnLockscreen;
@property(nonatomic, readonly) BOOL staysDisplayedOnLockscreen;
@property(nonatomic, readonly) BOOL ignoresDowntime;
@property(nonatomic, readonly) BOOL isCriticalAlert;
@property(nonatomic, readonly) BOOL ignoresDND;
@property(nonatomic, readonly) BOOL canInteractAtLockscreen;
@property(nonatomic, readonly) BOOL canColeasce;
@property(nonatomic) BOOL pendingInitialDisplay; // @synthesize pendingInitialDisplay;
@property(nonatomic) BOOL displayedFirstAtLockscreen; // @synthesize displayedFirstAtLockscreen;
@property(nonatomic) double dismissTime; // @synthesize dismissTime;
@property(nonatomic) double displayTime; // @synthesize displayTime;
@property(nonatomic, retain) NCNotificationWindow *window; // @synthesize window;
@property(nonatomic, readonly) unsigned long long sortBehavior;
@property(nonatomic, readonly) unsigned long long behavior;
@property(nonatomic, readonly) NCCARemoteSession *session; // @synthesize session;
@property(nonatomic, readonly) _TtC21NotificationCenterApp7AppInfo *app; // @synthesize app;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp14BannerDelegate_> delegate; // @synthesize delegate;

@end

