//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, _TtC21NotificationCenterApp33TodayViewListContainerPlaceholder;

@interface _TtC21NotificationCenterApp22TodayViewListContainer : NSViewController
{
    MISSING_TYPE *placeholder;
    MISSING_TYPE *dragging;
    MISSING_TYPE *look;
    MISSING_TYPE *contentController;
    MISSING_TYPE *headerController;
    MISSING_TYPE *_cardController;
}

+ (id)containerFrom:(id)arg1;
- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithHeader:(id)arg1 content:(id)arg2 cardLook:(long long)arg3;
@property(nonatomic, retain) NSViewController *headerController; // @synthesize headerController;
@property(nonatomic, readonly) NSViewController *contentController; // @synthesize contentController;
@property(nonatomic, readonly) BOOL hasCardLook;
@property(nonatomic) BOOL dragging; // @synthesize dragging;
@property(nonatomic, retain) _TtC21NotificationCenterApp33TodayViewListContainerPlaceholder *placeholder; // @synthesize placeholder;

@end

