//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp15SoundController : _TtCs12_SwiftObject
{
    MISSING_TYPE *unitTestPlayNSSound;
    MISSING_TYPE *unitTestPlayDefaultSound;
    MISSING_TYPE *unitTestPlayTone;
    MISSING_TYPE *_queue;
    MISSING_TYPE *_lookupQueue;
    MISSING_TYPE *_systemSounds;
    MISSING_TYPE *_systemUpdateTime;
    MISSING_TYPE *_soundStatus;
    MISSING_TYPE *_requestedSound;
    MISSING_TYPE *_requestSource;
    MISSING_TYPE *_soundPlaying;
    MISSING_TYPE *_lastPlayedTime;
}

@end

