//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp20ScreenTimeController : NSObject
{
    MISSING_TYPE *updateCallout;
    MISSING_TYPE *applications;
    MISSING_TYPE *policyMonitor;
    MISSING_TYPE *policiesByApplication;
    MISSING_TYPE *managementState;
    MISSING_TYPE *duetQueue;
    MISSING_TYPE *duetStore;
    MISSING_TYPE *duetStream;
    MISSING_TYPE *duetValueType;
}

- (void).cxx_destruct;
- (id)init;

@end

