//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@class MISSING_TYPE, NSString;
@protocol _TtP21NotificationCenterApp19AlertButtonDelegate_;

@interface _TtC21NotificationCenterApp11AlertButton : NSButton
{
    MISSING_TYPE *roundedEdges;
    MISSING_TYPE *alwaysDropdown;
    MISSING_TYPE *notificationAction;
    MISSING_TYPE *showingMenu;
    MISSING_TYPE *delegate;
    MISSING_TYPE *showsDropdownArrow;
    MISSING_TYPE *_buttonImage;
    MISSING_TYPE *_buttonTitle;
    MISSING_TYPE *_highlightView;
    MISSING_TYPE *_delayedPopupCell;
    MISSING_TYPE *_popupTimer;
    MISSING_TYPE *_menuShown;
    MISSING_TYPE *_observer;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layout;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)dismissPopupIfNecessary;
- (void)awakeFromNib;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
@property(nonatomic, copy) NSString *title;
@property(nonatomic) BOOL showsDropdownArrow; // @synthesize showsDropdownArrow;
@property(nonatomic, readonly) BOOL hasPopupMenu;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp19AlertButtonDelegate_> delegate; // @synthesize delegate;
@property(nonatomic) BOOL showingMenu; // @synthesize showingMenu;
@property(nonatomic, retain) id notificationAction; // @synthesize notificationAction;
@property(nonatomic) BOOL alwaysDropdown; // @synthesize alwaysDropdown;
@property(nonatomic) long long roundedEdges; // @synthesize roundedEdges;

@end

