//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCTodayItemViewController.h"

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp30NCTodayAccessoryViewController : NCTodayItemViewController
{
    MISSING_TYPE *accessoryController;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithItem:(id)arg1;

@end

