//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCRoundedWindowContentView.h"

#import "NSAccessibilityButton-Protocol.h"

@interface _TtC21NotificationCenterApp15AlertWindowView : NCRoundedWindowContentView <NSAccessibilityButton>
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)accessibilitySubrole;
- (id)accessibilityRoleDescription;
- (id)accessibilityTopLevelUIElement;
- (id)accessibilityWindow;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;

@end

