//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp30NotificationsContextRepository : _TtCs12_SwiftObject
{
    MISSING_TYPE *_recordReleased;
    MISSING_TYPE *_pendingActions;
    MISSING_TYPE *_actions;
    MISSING_TYPE *_loadingContexts;
    MISSING_TYPE *_notificationContexts;
    MISSING_TYPE *_releasedRecords;
    MISSING_TYPE *_queue;
    MISSING_TYPE *_releaseTimer;
    MISSING_TYPE *_concurrentQueue;
    MISSING_TYPE *_callouts;
}

@end

