//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSButton, NSImageView, NSLayoutConstraint, NSTextField;

@interface _TtC21NotificationCenterApp26NCNightShiftViewController : NSViewController
{
    MISSING_TYPE *reasonTopConstraint;
    MISSING_TYPE *reasonHeightConstraint;
    MISSING_TYPE *reasonTextField;
    MISSING_TYPE *button;
    MISSING_TYPE *image;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)buttonPressed:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSImageView *image; // @synthesize image;
@property(nonatomic, retain) NSButton *button; // @synthesize button;
@property(nonatomic, retain) NSTextField *reasonTextField; // @synthesize reasonTextField;
@property(nonatomic, retain) NSLayoutConstraint *reasonHeightConstraint; // @synthesize reasonHeightConstraint;
@property(nonatomic, retain) NSLayoutConstraint *reasonTopConstraint; // @synthesize reasonTopConstraint;

@end

