//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSButton, NSTextField;

@interface _TtC21NotificationCenterApp25NotificationsTableDateRow : NSViewController
{
    MISSING_TYPE *dateLabel;
    MISSING_TYPE *deleteButton;
    MISSING_TYPE *model;
    MISSING_TYPE *owner;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)deleteClicked:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) NSButton *deleteButton; // @synthesize deleteButton;
@property(nonatomic, retain) NSTextField *dateLabel; // @synthesize dateLabel;

@end

