//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp30NotificationsTableAccessoryRow : NSViewController
{
    MISSING_TYPE *cardCtrl;
    MISSING_TYPE *accCtrl;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)loadView;
- (id)init;

@end

