//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp22NotificationActionObjC : NSObject
{
    MISSING_TYPE *action;
    MISSING_TYPE *options;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) BOOL isReply;
@property(nonatomic, readonly) BOOL isLegacyCloseAction;
@property(nonatomic, readonly) BOOL isSnooze;

@end

