//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp27NCAccessoriesViewController : NSViewController
{
    MISSING_TYPE *lineView;
    MISSING_TYPE *dndViewController;
    MISSING_TYPE *nightShiftViewController;
    MISSING_TYPE *topConstraint;
    MISSING_TYPE *nightShiftHeight;
    MISSING_TYPE *updateTimer;
    MISSING_TYPE *nightShiftEnabled;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear;
- (void)loadView;

@end

