//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@interface _TtC21NotificationCenterAppP33_797F68900C2BE25D6CE6E2CC24F4BF6916_PopUpButtonCell : NSPopUpButtonCell
{
}

- (id)initWithCoder:(id)arg1;
- (id)initTextCell:(id)arg1 pullsDown:(BOOL)arg2;
- (struct CGPoint)_menuLocationForEvent:(id)arg1 inCellFrame:(struct CGRect)arg2 ofView:(id)arg3;
- (BOOL)_positionsMenuRelativeToRightEdge;

@end

