//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSImage, NSString;

@interface _TtC21NotificationCenterApp7AppInfo : NSObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *image;
    MISSING_TYPE *identifier;
    MISSING_TYPE *found;
    MISSING_TYPE *lastKnownPath;
    MISSING_TYPE *categories;
    MISSING_TYPE *notifications;
    MISSING_TYPE *appFoundCallback;
    MISSING_TYPE *appNotFoundCallback;
    MISSING_TYPE *type;
    MISSING_TYPE *notificationsAllowed;
    MISSING_TYPE *criticalNotificationsAllowed;
    MISSING_TYPE *shownInNotificationCenter;
    MISSING_TYPE *notificationsToShow;
    MISSING_TYPE *alertStyle;
    MISSING_TYPE *badgeIcons;
    MISSING_TYPE *playSounds;
    MISSING_TYPE *hiddenFromLockscreen;
    MISSING_TYPE *contentHidden;
    MISSING_TYPE *contentHiddenFromLockscreen;
    MISSING_TYPE *showsSummary;
    MISSING_TYPE *usesModernAPI;
    MISSING_TYPE *screenTimeRestricted;
    MISSING_TYPE *authorizations;
    MISSING_TYPE *latestNotificationUpdateTime;
    MISSING_TYPE *todaySummary;
    MISSING_TYPE *tomorrowSummary;
    MISSING_TYPE *_staticallyLoaded;
    MISSING_TYPE *_refreshing;
}

- (void).cxx_destruct;
- (id)init;
- (void)updateSettingsWithNsDictionary:(id)arg1;
- (id)getSettings;
- (id)initWithSystem:(id)arg1;
- (id)initWithStatically:(id)arg1 lastKnownPath:(id)arg2 type:(long long)arg3 name:(id)arg4 imageData:(id)arg5;
- (id)initWith:(id)arg1 lastKnownPath:(id)arg2 type:(long long)arg3 queue:(id)arg4;
@property(nonatomic, readonly) NSString *unprefixedIdentifier;
@property(nonatomic, readonly) BOOL isSystemApp;
@property(nonatomic) BOOL screenTimeRestricted; // @synthesize screenTimeRestricted;
@property(nonatomic) BOOL usesModernAPI; // @synthesize usesModernAPI;
@property(nonatomic, readonly) BOOL isAskPermissionsApp;
@property(nonatomic) BOOL contentHiddenFromLockscreen; // @synthesize contentHiddenFromLockscreen;
@property(nonatomic) BOOL contentHidden; // @synthesize contentHidden;
@property(nonatomic) BOOL hiddenFromLockscreen; // @synthesize hiddenFromLockscreen;
@property(nonatomic) BOOL playSounds; // @synthesize playSounds;
@property(nonatomic) BOOL badgeIcons; // @synthesize badgeIcons;
@property(nonatomic, readonly) long long rawAlertStyle;
@property(nonatomic) long long notificationsToShow; // @synthesize notificationsToShow;
@property(nonatomic) BOOL shownInNotificationCenter; // @synthesize shownInNotificationCenter;
@property(nonatomic) BOOL criticalNotificationsAllowed; // @synthesize criticalNotificationsAllowed;
@property(nonatomic) BOOL notificationsAllowed; // @synthesize notificationsAllowed;
@property(nonatomic, readonly) long long type; // @synthesize type;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, copy) NSString *lastKnownPath;
@property(nonatomic) BOOL found; // @synthesize found;
@property(nonatomic, readonly) NSString *identifier;
@property(nonatomic, retain) NSImage *image; // @synthesize image;
@property(nonatomic, copy) NSString *name;

@end

