//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NCNotificationWindow, NSArray, NSDate, NSDateComponents, NSImage, NSString, _TtC21NotificationCenterApp24NotificationCategoryObjC, _TtC21NotificationCenterApp25NotificationSummaryBanner, _TtC21NotificationCenterApp7AppInfo;
@protocol _TtP21NotificationCenterApp14BannerDelegate_;

@interface _TtC21NotificationCenterApp18NotificationBanner : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *app;
    MISSING_TYPE *category;
    MISSING_TYPE *behavior;
    MISSING_TYPE *remotePlugInIdentifier;
    MISSING_TYPE *remotePlugIn;
    MISSING_TYPE *displayTime;
    MISSING_TYPE *dismissTime;
    MISSING_TYPE *displayedFirstAtLockscreen;
    MISSING_TYPE *pendingInitialDisplay;
    MISSING_TYPE *canColeasce;
    MISSING_TYPE *registeredTalkingAlerts;
    MISSING_TYPE *creationOrder;
    MISSING_TYPE *progress;
    MISSING_TYPE *_cachedIdentityImage;
    MISSING_TYPE *_cachedStatusImage;
    MISSING_TYPE *_bannerWindow;
    MISSING_TYPE *_notification;
    MISSING_TYPE *_request;
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)dismissTimeWithLessThan:(double)arg1;
- (void)swapWith:(id)arg1;
- (void)clearWindow;
- (id)windowCreateIfNecessary;
@property(nonatomic, readonly) BOOL legacyDismissAfterDuration;
@property(nonatomic, readonly) BOOL legacyAllDayEvent;
@property(nonatomic, readonly) NSDateComponents *legacyEventDuration;
@property(nonatomic, readonly) NSDate *legacyEventDate;
@property(nonatomic, readonly) _TtC21NotificationCenterApp25NotificationSummaryBanner *asSummaryModel;
@property(nonatomic, readonly) NSString *actionsButtonTitle;
@property(nonatomic, readonly) NSString *hiddenContentBody;
@property(nonatomic, readonly) NSString *body;
@property(nonatomic, readonly) NSString *hiddenContentSubTitle;
@property(nonatomic, readonly) NSString *subtitle;
@property(nonatomic, readonly) NSString *hiddenContentTitle;
@property(nonatomic, readonly) NSString *title;
@property(nonatomic) double progress; // @synthesize progress;
@property(nonatomic, readonly) NSArray *peopleIdentifiers;
@property(nonatomic, readonly) NSImage *customStatusImage;
@property(nonatomic, readonly) unsigned long long legacyIdentityStyle;
@property(nonatomic, readonly) NSImage *identityImage;
@property(nonatomic, readonly) NSImage *identityBadgingImage;
@property(nonatomic, readonly) BOOL identityImageIsCustom;
@property(nonatomic, readonly) NSImage *contentImage;
@property(nonatomic, readonly) NSDate *deliveredDate;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic) long long creationOrder; // @synthesize creationOrder;
@property(nonatomic, readonly) BOOL isRemote;
@property(nonatomic) BOOL registeredTalkingAlerts; // @synthesize registeredTalkingAlerts;
@property(nonatomic, readonly) BOOL staysDisplayedOnLockscreen;
@property(nonatomic, readonly) BOOL showOnLockscreen;
@property(nonatomic, readonly) BOOL ignoresDowntime;
@property(nonatomic, readonly) BOOL ignoresDND;
@property(nonatomic, readonly) BOOL isCriticalAlert;
@property(nonatomic, readonly) BOOL canInteractAtLockscreen;
@property(nonatomic) BOOL canColeasce; // @synthesize canColeasce;
@property(nonatomic, readonly) BOOL isSummaryModel;
@property(nonatomic) BOOL pendingInitialDisplay; // @synthesize pendingInitialDisplay;
@property(nonatomic) BOOL displayedFirstAtLockscreen; // @synthesize displayedFirstAtLockscreen;
@property(nonatomic) double dismissTime; // @synthesize dismissTime;
@property(nonatomic) double displayTime; // @synthesize displayTime;
@property(nonatomic, readonly) NCNotificationWindow *window;
@property(nonatomic, readonly) unsigned long long sortBehavior;
@property(nonatomic) unsigned long long behavior; // @synthesize behavior;
@property(nonatomic, readonly) _TtC21NotificationCenterApp24NotificationCategoryObjC *category; // @synthesize category;
@property(nonatomic, readonly) _TtC21NotificationCenterApp7AppInfo *app; // @synthesize app;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp14BannerDelegate_> delegate; // @synthesize delegate;

@end

