//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp29BannerExtensionViewController.h"

@class MISSING_TYPE, NSString, NSTextView, NSView;

@interface _TtC21NotificationCenterApp25BannerReplyViewController : _TtC21NotificationCenterApp29BannerExtensionViewController
{
    MISSING_TYPE *replyTextView;
    MISSING_TYPE *_actionHandled;
    MISSING_TYPE *_hasText;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithBanner:(id)arg1 action:(id)arg2;
- (void)handleCancelButtonPress;
- (void)viewDidAppear;
- (void)viewDidLoad;
@property(nonatomic, readonly) NSView *firstResponder;
- (void)dealloc;
@property(nonatomic, readonly) NSString *expandedActionTitle;
@property(nonatomic, readonly) BOOL ready;
@property(nonatomic, retain) NSTextView *replyTextView; // @synthesize replyTextView;

@end

