//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp19NotificationTrigger : _TtCs12_SwiftObject
{
    MISSING_TYPE *storage;
}

@end

