//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp28NotificationsTableController.h"

#import "NCNotificationCenterTabProtocol-Protocol.h"

@interface _TtC21NotificationCenterApp28NotificationsTableController (NotificationCenterApp2) <NCNotificationCenterTabProtocol>
- (void)notificationCenterTabFirstResponderChangedFrom:(id)arg1 to:(id)arg2;
- (void)notificationCenterTabWasHidden;
- (void)notificationCenterTabWillBeHidden;
- (void)notificationCenterTabWillBeShown;
@end

