//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSWindow;
@protocol _TtP21NotificationCenterApp26BannerWindowLayoutDelegate_;

@interface _TtC21NotificationCenterApp28BannerWindowLayoutController : NSObject
{
    MISSING_TYPE *bannerWindowController;
    MISSING_TYPE *delegate;
    MISSING_TYPE *centerOpen;
    MISSING_TYPE *alertsDisabled;
    MISSING_TYPE *lockscreenMode;
    MISSING_TYPE *_screenUnlockTime;
    MISSING_TYPE *_screenLockedTime;
    MISSING_TYPE *_screenLockDisplayTime;
    MISSING_TYPE *_powerAssertionTime;
    MISSING_TYPE *_powerAssertionLastTime;
    MISSING_TYPE *_powerAssertionStartTime;
    MISSING_TYPE *_powerAssertionCount;
    MISSING_TYPE *_bannerExpireCalculateSource;
    MISSING_TYPE *_powerAssertionID;
    MISSING_TYPE *_bannerTime;
    MISSING_TYPE *_bannerTimeLockscreen;
    MISSING_TYPE *_bannerWithKey;
    MISSING_TYPE *_bannerExpireTimer;
    MISSING_TYPE *_queuedBannerTimer;
    MISSING_TYPE *_queuedBanners;
    MISSING_TYPE *_queuedBannersShouldBeDisplayed;
    MISSING_TYPE *_banners;
    MISSING_TYPE *_notesPerApp;
    MISSING_TYPE *_pendingRemovedAlertsWithExtension;
}

- (void).cxx_destruct;
- (id)init;
- (void)layoutWindowForScreenRect:(struct CGRect)arg1 visibleRect:(struct CGRect)arg2;
- (BOOL)switchKeyNotifictionWithReversed:(BOOL)arg1;
- (BOOL)canSwitchKeyNotifications;
- (id)initWithScreenFrame:(struct CGRect)arg1 visibleFrame:(struct CGRect)arg2 space:(unsigned long long)arg3;
@property(nonatomic) long long lockscreenMode; // @synthesize lockscreenMode;
@property(nonatomic) BOOL alertsDisabled; // @synthesize alertsDisabled;
@property(nonatomic) BOOL centerOpen; // @synthesize centerOpen;
@property(nonatomic, readonly) BOOL hasPowerAssertion;
@property(nonatomic, readonly) struct CGRect windowFrame;
@property(nonatomic, readonly) NSWindow *window;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp26BannerWindowLayoutDelegate_> delegate; // @synthesize delegate;

@end

