//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp25BannerReplyViewController.h"

#import "NSTextViewDelegate-Protocol.h"

@interface _TtC21NotificationCenterApp25BannerReplyViewController (NotificationCenterApp) <NSTextViewDelegate>
- (void)textDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
@end

