//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSButton, NSImageView, NSLayoutConstraint, NSString, NSTextField, NSView;

@interface _TtC21NotificationCenterApp30ScreenTimeWidgetViewController : NSViewController
{
    MISSING_TYPE *hourglassImageView;
    MISSING_TYPE *buttonContainer;
    MISSING_TYPE *buttonBottomConstraint;
    MISSING_TYPE *buttonContainerHeightConstraint;
    MISSING_TYPE *buttonView;
    MISSING_TYPE *descriptionTextField;
    MISSING_TYPE *getMoreTimeButton;
    MISSING_TYPE *askForMoreTimeButton;
    MISSING_TYPE *showsButtons;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)askForMoreTime:(id)arg1;
- (void)getMoreTime:(id)arg1;
@property(nonatomic) BOOL showsButtons; // @synthesize showsButtons;
@property(nonatomic, readonly) NSString *nibName;
@property(nonatomic) __weak NSButton *askForMoreTimeButton; // @synthesize askForMoreTimeButton;
@property(nonatomic) __weak NSButton *getMoreTimeButton; // @synthesize getMoreTimeButton;
@property(nonatomic) __weak NSTextField *descriptionTextField; // @synthesize descriptionTextField;
@property(nonatomic, retain) NSView *buttonView; // @synthesize buttonView;
@property(nonatomic) __weak NSLayoutConstraint *buttonContainerHeightConstraint; // @synthesize buttonContainerHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *buttonBottomConstraint; // @synthesize buttonBottomConstraint;
@property(nonatomic) __weak NSView *buttonContainer; // @synthesize buttonContainer;
@property(nonatomic) __weak NSImageView *hourglassImageView; // @synthesize hourglassImageView;

@end

