//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NCTableView, NSScrollView, NSTextField;

@interface _TtC21NotificationCenterApp28NotificationsTableController : NSViewController
{
    MISSING_TYPE *dataSource;
    MISSING_TYPE *_forDebug;
    MISSING_TYPE *_scrollView;
    MISSING_TYPE *_failedToConnect;
    MISSING_TYPE *_tableCache;
    MISSING_TYPE *_tableHidden;
    MISSING_TYPE *_tableNeedsReload;
    MISSING_TYPE *_includeAccessories;
    MISSING_TYPE *_mouseInRow;
    MISSING_TYPE *_reloadTimer;
    MISSING_TYPE *tableView;
    MISSING_TYPE *scrollView;
    MISSING_TYPE *noMessageTF;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) NSTextField *noMessageTF; // @synthesize noMessageTF;
@property(nonatomic, retain) NSScrollView *scrollView; // @synthesize scrollView;
@property(nonatomic, retain) NCTableView *tableView; // @synthesize tableView;
- (void)rowPressed:(id)arg1;
- (void)_tableScrolled;
- (void)mouseMoved;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithWidth:(double)arg1 dndRow:(BOOL)arg2 debug:(BOOL)arg3;

@end

