//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp28BannerWindowLayoutController.h"

#import "NCBannerWindowControllerDelegate-Protocol.h"

@interface _TtC21NotificationCenterApp28BannerWindowLayoutController (NotificationCenterApp1) <NCBannerWindowControllerDelegate>
- (double)bannerWindowOpenOffset:(id)arg1;
- (void)bannerWindowOrderedOut:(id)arg1;
- (void)bannerWindow:(id)arg1 bannersHiddenDueToOverflow:(id)arg2;
@end

