//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCTodayRemoteItem.h"

@class MISSING_TYPE, NSString;

@interface _TtC21NotificationCenterApp12TodaySnippet : NCTodayRemoteItem
{
    MISSING_TYPE *snippetIdentifier;
    MISSING_TYPE *imagePath;
}

+ (id)compositeIdentifier:(id)arg1 identifier:(id)arg2;
- (void).cxx_destruct;
- (id)init;
- (id)configurationInfo;
- (id)initWithIdentifier:(id)arg1 title:(id)arg2 imagePath:(id)arg3 remotePlugin:(id)arg4;
@property(nonatomic, readonly) BOOL configurationShowAsNew;
@property(nonatomic, readonly) NSString *messageTracerIdentifier;
@property(nonatomic) BOOL enabled;
@property(nonatomic, readonly) BOOL isSnippet;
@property(nonatomic, readonly) NSString *snippetIdentifier;

@end

