//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCE16EyeCandyGraphicsaSo11CGRegionRefP33_E25F4199FE41BDF67B45AA15EB701DE616CGRegionIterator : _TtCs12_SwiftObject
{
    MISSING_TYPE *enumerator;
}

@end

