//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp28BannerWindowLayoutController.h"

#import "NCCAControllerDelegate-Protocol.h"

@interface _TtC21NotificationCenterApp28BannerWindowLayoutController (NotificationCenterApp2) <NCCAControllerDelegate>
- (void)NCCAController:(id)arg1 dismissRemoteSession:(id)arg2 withAnimation:(unsigned long long)arg3;
- (void)NCCAController:(id)arg1 presentRemoteSession:(id)arg2;
- (void)NCCAController:(id)arg1 releaseKeySession:(id)arg2;
- (void)NCCAController:(id)arg1 makeSessionKey:(id)arg2;
@end

