//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp28NotificationRecordContext_NC : _TtCs12_SwiftObject
{
    MISSING_TYPE *recordUUID;
    MISSING_TYPE *appIdentifier;
    MISSING_TYPE *customAppIcon;
    MISSING_TYPE *customIconBadge;
    MISSING_TYPE *contentThumbnail;
    MISSING_TYPE *localizations;
    MISSING_TYPE *_release;
}

@end

