//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface _TtC21NotificationCenterApp15AlertButtonCell : NSButtonCell
{
}

- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityChildren;
- (id)accessibilityShownMenu;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;

@end

