//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC21NotificationCenterApp18NotificationBanner.h"

@class MISSING_TYPE, NSImage, NSString;

@interface _TtC21NotificationCenterApp25NotificationSummaryBanner : _TtC21NotificationCenterApp18NotificationBanner
{
    MISSING_TYPE *records;
    MISSING_TYPE *additionalCount;
    MISSING_TYPE *_commonTitle;
    MISSING_TYPE *_cachedBody;
}

- (void).cxx_destruct;
@property(nonatomic, readonly) NSString *hiddenContentBody;
@property(nonatomic, readonly) NSString *body;
@property(nonatomic, readonly) NSString *subtitle;
@property(nonatomic, readonly) NSString *title;
@property(nonatomic, readonly) NSImage *customStatusImage;
@property(nonatomic, readonly) NSImage *contentImage;
@property(nonatomic, readonly) unsigned long long legacyIdentityStyle;
@property(nonatomic, readonly) NSImage *identityImage;
@property(nonatomic, readonly) BOOL identityImageIsCustom;
@property(nonatomic, readonly) _TtC21NotificationCenterApp25NotificationSummaryBanner *asSummaryModel;
@property(nonatomic, readonly) BOOL isSummaryModel;
@property(nonatomic, readonly) NSString *description;

@end

