//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp4Line : NSView
{
    MISSING_TYPE *box;
    MISSING_TYPE *leftTouchesEdge;
    MISSING_TYPE *rightTouchesEdge;
    MISSING_TYPE *topTouchesEdge;
    MISSING_TYPE *bottomTouchesEdge;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layout;
@property(nonatomic) BOOL bottomTouchesEdge; // @synthesize bottomTouchesEdge;
@property(nonatomic) BOOL topTouchesEdge; // @synthesize topTouchesEdge;
@property(nonatomic) BOOL rightTouchesEdge; // @synthesize rightTouchesEdge;
@property(nonatomic) BOOL leftTouchesEdge; // @synthesize leftTouchesEdge;

@end

