//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class MISSING_TYPE, NSString;
@protocol _TtP21NotificationCenterApp21NCDebugWindowDelegate_;

@interface _TtC21NotificationCenterApp13NCDebugWindow : NSWindowController
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *dndModeEnabled;
    MISSING_TYPE *screenLockMode;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
@property(nonatomic, readonly) NSString *windowNibName;
@property(nonatomic) long long screenLockMode; // @synthesize screenLockMode;
@property(nonatomic) BOOL dndModeEnabled; // @synthesize dndModeEnabled;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp21NCDebugWindowDelegate_> delegate; // @synthesize delegate;

@end

