//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray;

@interface _TtC21NotificationCenterApp24NotificationCategoryObjC : NSObject
{
    MISSING_TYPE *category;
    MISSING_TYPE *actions;
    MISSING_TYPE *options;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) BOOL legacyActionIsSnooze;
@property(nonatomic, readonly) BOOL alwaysShowActionMenu;
@property(nonatomic, readonly) BOOL bannerShowsButtons;
@property(nonatomic, readonly) BOOL legacyBehaviors;
@property(nonatomic, readonly) NSArray *actions;

@end

