//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSLayoutConstraint, _TtC21NotificationCenterApp22TodayViewListContainer;

@interface _TtC21NotificationCenterApp33TodayViewListContainerPlaceholder : NSViewController
{
    MISSING_TYPE *heightConstraint;
    MISSING_TYPE *representedContainer;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithRepresentedContainer:(id)arg1;
@property(nonatomic, retain) _TtC21NotificationCenterApp22TodayViewListContainer *representedContainer; // @synthesize representedContainer;
@property(nonatomic, retain) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint;

@end

