//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class MISSING_TYPE;

@interface _TtC21NotificationCenterApp9TextField : NSTextField
{
    MISSING_TYPE *mediumSystemFontOfSize;
    MISSING_TYPE *clipWidth;
    MISSING_TYPE *_fadeGradient;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
@property(nonatomic) double clipWidth; // @synthesize clipWidth;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
@property(nonatomic) double mediumSystemFontOfSize; // @synthesize mediumSystemFontOfSize;

@end

