//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC21NotificationCenterApp29BannerExtensionViewController;

@protocol _TtP21NotificationCenterApp23BannerExtensionDelegate_
- (void)bannerExtensionControllerHideExtensionWithController:(_TtC21NotificationCenterApp29BannerExtensionViewController *)arg1;
- (void)bannerExtensionControllerClosedWithController:(_TtC21NotificationCenterApp29BannerExtensionViewController *)arg1;
- (void)bannerExtensionControllerReadyWithController:(_TtC21NotificationCenterApp29BannerExtensionViewController *)arg1;
@end

