//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC21NotificationCenterApp11AlertButton;

@protocol _TtP21NotificationCenterApp19AlertButtonDelegate_
- (void)alertButtonItemSelectedWithContext:(id)arg1;
- (void)alertButtonCreateItemWithButton:(_TtC21NotificationCenterApp11AlertButton *)arg1:(void (^)(NSString *, id))arg2;
- (BOOL)alertButtonHasDelayedMenuWithButton:(_TtC21NotificationCenterApp11AlertButton *)arg1;
@end

