//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCNotificationWindow, NSDate, NSImage, _TtC21NotificationCenterApp25NotificationSummaryBanner, _TtC21NotificationCenterApp7AppInfo;
@protocol _TtP21NotificationCenterApp11BannerModel_, _TtP21NotificationCenterApp14BannerDelegate_;

@protocol _TtP21NotificationCenterApp11BannerModel_
- (BOOL)dismissTimeWithLessThan:(double)arg1;
- (void)swapWith:(id <_TtP21NotificationCenterApp11BannerModel_>)arg1;
- (void)clearWindow;
- (NCNotificationWindow *)windowCreateIfNecessary;
@property(nonatomic, readonly) NSDate *deliveredDate;
@property(nonatomic, readonly) BOOL isSummaryModel;
@property(nonatomic, readonly) _TtC21NotificationCenterApp25NotificationSummaryBanner *asSummaryModel;
@property(nonatomic, readonly) long long creationOrder;
@property(nonatomic) BOOL registeredTalkingAlerts;
@property(nonatomic, readonly) NSImage *identityBadgingImage;
@property(nonatomic, readonly) BOOL isCriticalAlert;
@property(nonatomic, readonly) BOOL isRemote;
@property(nonatomic, readonly) BOOL staysDisplayedOnLockscreen;
@property(nonatomic, readonly) BOOL ignoresDowntime;
@property(nonatomic, readonly) BOOL ignoresDND;
@property(nonatomic, readonly) BOOL canInteractAtLockscreen;
@property(nonatomic, readonly) BOOL canColeasce;
@property(nonatomic) BOOL pendingInitialDisplay;
@property(nonatomic) BOOL displayedFirstAtLockscreen;
@property(nonatomic, readonly) BOOL showOnLockscreen;
@property(nonatomic) double dismissTime;
@property(nonatomic) double displayTime;
@property(nonatomic, readonly) NCNotificationWindow *window;
@property(nonatomic, readonly) unsigned long long sortBehavior;
@property(nonatomic, readonly) unsigned long long behavior;
@property(nonatomic, readonly) _TtC21NotificationCenterApp7AppInfo *app;
@property(nonatomic, retain) id <_TtP21NotificationCenterApp14BannerDelegate_> delegate;
@end

