//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class _TtC21NotificationCenterApp13NCDebugWindow;

@protocol _TtP21NotificationCenterApp21NCDebugWindowDelegate_
- (void)debugWindowScreenlockModeChanged:(_TtC21NotificationCenterApp13NCDebugWindow *)arg1;
- (void)debugWindowDoNotDisturbModeChanged:(_TtC21NotificationCenterApp13NCDebugWindow *)arg1;
@end

