//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP21NotificationCenterApp26BannerWindowLayoutDelegate_
@property(nonatomic, readonly) double windowLayoutAlertOffset;
@end

