//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NCBannerViewController;

@interface NCBannerView : NSView
{
    NCBannerViewController *_owner;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NCBannerViewController *owner; // @synthesize owner=_owner;
- (void)updateConstraints;
- (void)awakeFromNib;

@end

