//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCBannerAnimation.h"

@interface NCBannerAnimationHorizontalIn : NCBannerAnimation
{
    double _originalHorizontalConstant;
}

+ (double)defaultDuration;
- (void)start;
- (id)initWithWindow:(id)arg1 type:(unsigned long long)arg2 delegate:(id)arg3 duration:(double)arg4 transitionType:(unsigned long long)arg5;

@end

