//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCBannerWindowController, NSArray;

@protocol NCBannerWindowControllerDelegate
- (double)bannerWindowOpenOffset:(NCBannerWindowController *)arg1;
- (void)bannerWindow:(NCBannerWindowController *)arg1 bannersHiddenDueToOverflow:(NSArray *)arg2;
- (void)bannerWindowOrderedOut:(NCBannerWindowController *)arg1;
@end

