//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface NCButtonCell : NSButtonCell
{
    struct CGSize _layoutImageSize;
}

@property(nonatomic) struct CGSize layoutImageSize; // @synthesize layoutImageSize=_layoutImageSize;
- (void)drawFocusRingMaskWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;

@end

