//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ViewBridge/NSRemoteViewController.h>

@class _NCCAHostViewBridgeControllerProxy;
@protocol NCServiceViewHostProtocol;

@interface NCCAHostViewBridgeController : NSRemoteViewController
{
    _NCCAHostViewBridgeControllerProxy *_proxy;
    id <NCServiceViewHostProtocol> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <NCServiceViewHostProtocol> delegate; // @synthesize delegate=_delegate;
- (id)_proxyCreateIfNecessary;
- (id)exportedObject;
- (id)exportedInterface;
- (id)serviceViewControllerInterface;

@end

