//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class NSMutableDictionary, NSString, NSXPCListener;
@protocol NCCAControllerDelegate;

@interface NCCAController : NSObject <NSXPCListenerDelegate>
{
    NSXPCListener *_listener;
    NSMutableDictionary *_sessions;
    id <NCCAControllerDelegate> _delegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property __weak id <NCCAControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)ncReleaseKeyAlert:(id)arg1;
- (void)ncMakeKeyAlert:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)ncDismissAlert:(id)arg1 withAnimation:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)ncActuallyPresentRemoteAlert:(id)arg1;
- (void)ncRequestPresentationOfRemoteAlert:(id)arg1 options:(id)arg2 withVBEndpoint:(id)arg3;
- (void)_incomingConnectionInterrupted:(id)arg1;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)_bundleIdentifierForConnection:(id)arg1;
- (void)dismissAlert:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

