//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

#import "NCMaterialDelegate-Protocol.h"

@interface NCConfigButton : NSButton <NCMaterialDelegate>
{
    _Bool _showsNewIndicator;
    double _titleWidth;
}

+ (Class)cellClass;
@property(nonatomic) double titleWidth; // @synthesize titleWidth=_titleWidth;
@property(nonatomic) _Bool showsNewIndicator; // @synthesize showsNewIndicator=_showsNewIndicator;
- (void)_setIndicatorImage;
- (struct CGSize)intrinsicContentSize;
- (void)setTitle:(id)arg1;
- (void)awakeFromNib;
- (void)appearanceChanged:(_Bool)arg1;
- (void)materialChanged:(unsigned char)arg1;
- (void)dealloc;

@end

