//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSImageView, NSLayoutConstraint, NSSwitch, NSTextField;

@interface NCDNDViewController : NSViewController
{
    NSLayoutConstraint *_reasonTopConstraint;
    NSLayoutConstraint *_reasonHeightConstraint;
    NSTextField *_reasonTextField;
    NSSwitch *_dndButton;
    NSImageView *_dndImage;
}

- (void).cxx_destruct;
@property(nonatomic) NSImageView *dndImage; // @synthesize dndImage=_dndImage;
@property(nonatomic) NSSwitch *dndButton; // @synthesize dndButton=_dndButton;
@property(nonatomic) NSTextField *reasonTextField; // @synthesize reasonTextField=_reasonTextField;
@property(nonatomic) NSLayoutConstraint *reasonHeightConstraint; // @synthesize reasonHeightConstraint=_reasonHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *reasonTopConstraint; // @synthesize reasonTopConstraint=_reasonTopConstraint;
- (void)dndButtonPressed:(id)arg1;
- (void)_updateDNDButton;
- (void)_updateDNDReason;
- (void)viewDidLoad;

@end

