//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSWindow, NSXPCConnection;
@protocol OS_xpc_object;

@interface NCDockCommunication : NSObject
{
    BOOL _needsAuthentication;
    BOOL _serverConnectionFailure;
    BOOL _debugShieldWindows;
    NSObject<OS_xpc_object> *_connection;
    double _centerWidth;
    unsigned long long _notificationSpaceID;
    unsigned int _lastDisplay;
    NSWindow *_mainWindow;
    NSWindow *_shieldWindow;
    NSWindow *_alertWindow;
    NSSet *_dockControlledWIDs;
    unsigned int _alertWID;
    NSXPCConnection *_dockConnection;
    _Bool _waitingForReconnect;
}

+ (void)dockAlive;
+ (id)dock;
- (void).cxx_destruct;
- (void)_setupDockConnection;
- (void)_disconnected;
- (void)_dockBackAlive;
- (void)ncPing:(CDUnknownBlockType)arg1;
- (void)ncToggleNotificationCenterOnDisplay:(int)arg1;
- (void)ncCloseNotificationCenterImmediately:(_Bool)arg1;
- (void)tellDockStateChanged:(_Bool)arg1;
- (void)tellDockAboutAlertWindow:(id)arg1;
- (id)init;

@end

