//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_source;

@interface NCHotKey : NSObject
{
    unsigned int _cid;
    NSObject<OS_dispatch_source> *_source;
    void *_lsNoteID;
    double _openTime;
    CDUnknownBlockType _changeBlock;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)_handleEvents;
- (void)setFocusChangeRect:(struct CGRect)arg1 changeBlock:(CDUnknownBlockType)arg2;
- (void)updateEventMaskWithRect:(struct CGRect)arg1;
- (void)_registerBackgroundEventMaskWithIgnoredRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)init;

@end

