//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class NSString;

@interface NCMaterialLayer : CALayer
{
    NSString *_groupName;
    CALayer *_backdropLayer;
    CALayer *_tintLayer;
    unsigned char _materialStyle;
    unsigned long long _material;
}

+ (_Bool)useDarkLook;
+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) unsigned char materialStyle; // @synthesize materialStyle=_materialStyle;
@property(nonatomic) unsigned long long material; // @synthesize material=_material;
- (void)_buildVibrantLayerTree:(unsigned long long)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithMaterial:(unsigned long long)arg1 groupName:(id)arg2 style:(unsigned char)arg3;

@end

