//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NCMessageTracer : NSObject
{
    double _openTime;
    double _todayViewStartTime;
    double _notificationsViewStartTime;
    int _secondsInTodayView;
    int _secondsInNotificationView;
    _Bool _opened;
    unsigned long long _activeViewType;
}

+ (id)defaultMessageTracer;
@property(nonatomic) _Bool opened; // @synthesize opened=_opened;
@property(nonatomic) unsigned long long activeViewType; // @synthesize activeViewType=_activeViewType;
- (void)nightShiftSwitchedOff;
- (void)nightShiftSwitchedOn;
- (void)logActiveWidgets:(id)arg1;
- (void)notificationCenterSwitchedToView:(unsigned long long)arg1;
- (void)notificationCenterClosed;
- (void)notificationCenterOpened;
- (id)init;

@end

