//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, NSXPCListenerEndpoint;

@protocol NCNotificationExtensionProviderHostProtocol
- (void)extensionProviderDisplayExtension:(NSString *)arg1 userInfo:(NSDictionary *)arg2 extensionEndpoint:(NSXPCListenerEndpoint *)arg3;
@end

