//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCConnectionDelegate-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class NSString, NSXPCConnection, NSXPCListener;
@protocol NCWidgetPrefServerInterface, NCWidgetsPrefClientInterface;

@interface NCNotificationCenterPrefsConnection : NSObject <NSXPCConnectionDelegate, NSXPCListenerDelegate>
{
    NSXPCListener *_listener;
    NSXPCConnection *_connection;
    id <NCWidgetPrefServerInterface> _todayPrefsDelegate;
}

+ (id)sharedConnection;
- (void).cxx_destruct;
@property(nonatomic) __weak id <NCWidgetPrefServerInterface> todayPrefsDelegate; // @synthesize todayPrefsDelegate=_todayPrefsDelegate;
- (void)notifyOfChange;
- (void)connection:(id)arg1 handleInvocation:(id)arg2 isReply:(BOOL)arg3;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)_disconnected;
@property(readonly, nonatomic) id <NCWidgetsPrefClientInterface> todayPrefClient;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

