//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class CALayer;

@interface NCNotificationTabContainer : NSView
{
    CALayer *_dividerLine;
    _Bool _showDivider;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool showDivider; // @synthesize showDivider=_showDivider;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;

@end

