//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
#import <Foundation/Foundation.h>
#import "NSObject-Protocol.h"

@protocol NCNotificationCenterMenu 
- (void)ncMenuDNDToggle;
- (void)ncMenuMouseUp;
- (void)ncMenuMouseDown;
- (void)ncMenugetInitialState:(void (^)(_Bool))arg1;
@end

