//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCNotificationCenterWindowAnimator, NSWindow;

@protocol NCNotificationCenterWindowAnimatorProtocol 
- (void)ncWindowAnimatorCloseCompleted:(NCNotificationCenterWindowAnimator *)arg1;
- (void)ncWindowAnimatorOpenCompleted:(NCNotificationCenterWindowAnimator *)arg1;
- (void)ncWindowAnimatorWillClose:(NCNotificationCenterWindowAnimator *)arg1;
- (void)ncWindowAnimatorWillOpen:(NCNotificationCenterWindowAnimator *)arg1 fluid:(_Bool)arg2 onDisplay:(unsigned int)arg3;
- (BOOL)ncWindowAnimatorShouldOpen:(NCNotificationCenterWindowAnimator *)arg1;
- (NSWindow *)ncWindowAnimatorAlertWindowToMove:(NCNotificationCenterWindowAnimator *)arg1 startFrame:(struct CGRect *)arg2;
- (NSWindow *)ncWindowAnimatorWindowToAnimate:(NCNotificationCenterWindowAnimator *)arg1;
@end

