//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSUUID, NSXPCListenerEndpoint;

@protocol NCNotificationCenterProtocol
- (void)ncReleaseKeyAlert:(NSUUID *)arg1;
- (void)ncMakeKeyAlert:(NSUUID *)arg1 completion:(void (^)(void))arg2;
- (void)ncDismissAlert:(NSUUID *)arg1 withAnimation:(unsigned long long)arg2 completion:(void (^)(void))arg3;
- (void)ncActuallyPresentRemoteAlert:(NSUUID *)arg1;
- (void)ncRequestPresentationOfRemoteAlert:(NSUUID *)arg1 options:(NSDictionary *)arg2 withVBEndpoint:(NSXPCListenerEndpoint *)arg3;
- (void)ncPing:(void (^)(void))arg1;
@end

