//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@interface NCNotificationRowView : NSTableRowView
{
}

- (void)drawSelectionInRect:(struct CGRect)arg1;
- (BOOL)isOpaque;

@end

