//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCRemoteViewHostViewController, NSData, NSDictionary;

@protocol NCRemoteViewHostViewControllerDelegate
- (void)remoteViewController:(NCRemoteViewHostViewController *)arg1 contentSizeChanged:(struct CGSize)arg2;
- (void)remoteViewController:(NCRemoteViewHostViewController *)arg1 liveStatusChanged:(_Bool)arg2;

@optional
- (void)remoteViewController:(NCRemoteViewHostViewController *)arg1 saveSnapshotData:(NSData *)arg2 withScale:(double)arg3 dark:(_Bool)arg4;
- (void)remoteViewController:(NCRemoteViewHostViewController *)arg1 loadSnapshotAtScale:(double)arg2 dark:(_Bool)arg3 data:(void (^)(NSData *))arg4;
- (BOOL)remoteViewControllerSupportsSnapshot:(NCRemoteViewHostViewController *)arg1;
- (void)remoteViewController:(NCRemoteViewHostViewController *)arg1 readyWithConfiguration:(NSDictionary *)arg2;
@end

