//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@class NSBundle;

@interface NCRelativeDateTransformer : NSValueTransformer
{
    NSBundle *bundleForLocalization;
    BOOL _longFormat;
}

+ (Class)transformedValueClass;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSBundle *bundleForLocalization; // @synthesize bundleForLocalization;
- (id)_transformedValue:(id)arg1 allDay:(BOOL)arg2 duration:(id)arg3 isRelative:(_Bool *)arg4;
- (id)transformedValue:(id)arg1;
- (id)snoozeStringForInterval:(double)arg1 before:(_Bool)arg2;
- (id)stringForDate:(id)arg1 allDay:(BOOL)arg2;
- (id)stringForDate:(id)arg1 allDay:(BOOL)arg2 duration:(id)arg3 isRelative:(_Bool *)arg4;
- (id)initWithLocalizerBundle:(id)arg1 longFormat:(BOOL)arg2;

@end

