//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@interface NCReplyTextView : NSTextView
{
}

- (id)itemsForSharingServiceInRanges:(id)arg1;
- (BOOL)becomeFirstResponder;
- (void)didChangeText;
- (struct CGSize)intrinsicContentSize;
- (void)awakeFromNib;

@end

