//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCNotificationWindow.h"

@class _TtC21NotificationCenterApp12RemoteBanner;

@interface NCRemoteNotificationWindow : NCNotificationWindow
{
    _Bool _removalDelayed;
    id _strongSelf;
    _Bool _live;
    _TtC21NotificationCenterApp12RemoteBanner *_remoteAlertModel;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool live; // @synthesize live=_live;
@property(readonly) _TtC21NotificationCenterApp12RemoteBanner *remoteAlertModel; // @synthesize remoteAlertModel=_remoteAlertModel;
- (void)windowMadeKey;
- (void)windowAnimateOutComplete;
- (void)windowAnimateInComplete;
- (void)reactivate;
- (unsigned long long)maxNotificationHeight;
- (id)nibName;
- (BOOL)loadView;
- (void)dealloc;
- (id)initWithModel:(id)arg1;

@end

