//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCRoundedWindowContentView, NSEvent;

@protocol NCRoundedWindowContentDelegate

@optional
- (void)contentView:(NCRoundedWindowContentView *)arg1 expandByPercent:(float)arg2;
- (BOOL)contentView:(NCRoundedWindowContentView *)arg1 edgeCanBeDragged:(char *)arg2 down:(char *)arg3;
- (void)contentViewEdgeDoubleClicked:(NCRoundedWindowContentView *)arg1;
- (void)contentView:(NCRoundedWindowContentView *)arg1 velocity:(double)arg2 draggedCompleted:(BOOL)arg3;
- (void)contentView:(NCRoundedWindowContentView *)arg1 dragged:(NSEvent *)arg2 onBottomEdge:(BOOL)arg3;
- (BOOL)contentView:(NCRoundedWindowContentView *)arg1 dragStarted:(NSEvent *)arg2 onBottomEdge:(BOOL)arg3;
- (void)contentViewUpdateConstraints:(NCRoundedWindowContentView *)arg1;
- (void)contentViewDidChangeOrigin:(NCRoundedWindowContentView *)arg1;
- (void)contentViewLayedOut:(NCRoundedWindowContentView *)arg1;
- (BOOL)contentView:(NCRoundedWindowContentView *)arg1 scrolled:(NSEvent *)arg2;
- (void)contentViewCloseButtonClicked:(NCRoundedWindowContentView *)arg1;
- (void)contentView:(NCRoundedWindowContentView *)arg1 mouseEntered:(BOOL)arg2;
- (void)contentView:(NCRoundedWindowContentView *)arg1 mouseClicked:(long long)arg2;
@end

