//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class NSShadow;

@interface NCShadowTextFieldCell : NSTextFieldCell
{
    BOOL _drawsShadow;
    NSShadow *_shadow;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSShadow *shadow; // @synthesize shadow=_shadow;
@property(nonatomic) BOOL drawsShadow; // @synthesize drawsShadow=_drawsShadow;
- (void)layoutLayerWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (unsigned long long)fontDilationStyle;
- (id)_textAttributes;
- (void)awakeFromNib;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

