//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSView;

@interface NCTableCellView : NSTableCellView
{
    NSView *_innerLayoutView;
}

@property(nonatomic) NSView *innerLayoutView; // @synthesize innerLayoutView=_innerLayoutView;
@property(readonly, nonatomic) double leftMarginWidth;

@end

