//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCTCCAlertViewController, NCTCCProvider, NSString;

@protocol NCTCCProviderDelegate
- (void)tccProvider:(NCTCCProvider *)arg1 dismissAlert:(NCTCCAlertViewController *)arg2;
- (_Bool)tccProvider:(NCTCCProvider *)arg1 presentAlert:(NCTCCAlertViewController *)arg2 forBundleID:(NSString *)arg3 andProcessID:(int)arg4;
- (void)tccProviderConnectionDidClose:(NCTCCProvider *)arg1;
@end

