//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCTodayItem.h"

@class NCRemotePlugIn;

@interface NCTodayRemoteItem : NCTodayItem
{
    NCRemotePlugIn *_remotePlugIn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NCRemotePlugIn *remotePlugIn; // @synthesize remotePlugIn=_remotePlugIn;
- (BOOL)configurationShowAsNew;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)enabled;
- (_Bool)isRemoteItem;

@end

