//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSButton, NSImageView, NSLayoutConstraint, NSTextField;

@interface NCTodaySummaryItemController : NSViewController
{
    NSLayoutConstraint *_heightConstraint;
    NSTextField *_textField;
    NSButton *_actionButton;
    NSImageView *_imageView;
}

@property(nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) NSButton *actionButton; // @synthesize actionButton=_actionButton;
@property(nonatomic) NSTextField *textField; // @synthesize textField=_textField;
@property(nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
- (void)setRepresentedObject:(id)arg1;
- (void)summaryClicked:(id)arg1;
- (void)awakeFromNib;

@end

