//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCTodayItemViewController;

@protocol NCTodayItemViewControllerDelegate
- (void)todayItemViewControllerAccessibilityPressedEdit:(NCTodayItemViewController *)arg1;
- (void)todayItemViewControllerIsNotLive:(NCTodayItemViewController *)arg1;
- (void)todayItemViewControllerIsLive:(NCTodayItemViewController *)arg1;
- (void)todayItemViewController:(NCTodayItemViewController *)arg1 sizeChangedForceUpdate:(_Bool)arg2;
- (void)todayItemViewController:(NCTodayItemViewController *)arg1 hasContentChanged:(_Bool)arg2;
- (void)todayItemViewController:(NCTodayItemViewController *)arg1 widgetModeChanged:(long long)arg2;
@end

