//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCTodayItem, NCTodayListController, NSViewController;
@protocol NCTodayListControllerTarget;

@protocol NCTodayListControllerDelegate

@optional
- (id <NCTodayListControllerTarget>)todayListControllerTarget:(NCTodayListController *)arg1;
- (void)todayListController:(NCTodayListController *)arg1 dropOfControllerCancelled:(NSViewController *)arg2;
- (void)todayListController:(NCTodayListController *)arg1 sourceDropCompleted:(NSViewController *)arg2;
- (void)todayListController:(NCTodayListController *)arg1 destinationDropCompleted:(NSViewController *)arg2 afterController:(NSViewController *)arg3;
- (void)todayListController:(NCTodayListController *)arg1 controllerForDropOfItem:(NCTodayItem *)arg2 fromList:(NCTodayListController *)arg3 block:(void (^)(NSViewController *, NSViewController *, unsigned long long, long long))arg4;
- (void)todayListController:(NCTodayListController *)arg1 didStartDragForController:(NSViewController *)arg2;
- (void)todayListController:(NCTodayListController *)arg1 didMoveController:(NSViewController *)arg2 toIndex:(unsigned long long)arg3;
- (BOOL)todayListController:(NCTodayListController *)arg1 canDragController:(NSViewController *)arg2 toIndex:(unsigned long long)arg3;
- (BOOL)todayListController:(NCTodayListController *)arg1 canDragController:(NSViewController *)arg2 fromHeader:(_Bool)arg3;
- (NCTodayItem *)todayListControllerTodayItemForController:(NSViewController *)arg1;
@end

