//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCTodayItemViewControllerDelegate-Protocol.h"

@class NCTodayHeaderViewController;

@protocol NCTodayHeaderDelegate <NCTodayItemViewControllerDelegate>
- (void)todayHeaderEditPressed:(NCTodayHeaderViewController *)arg1;
- (void)todayHeaderDeletePressed:(NCTodayHeaderViewController *)arg1;
@end

