//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NCTodayItemViewController.h"

@class NCDNDViewController, NSLayoutConstraint;

@interface NCTodayDNDViewController : NCTodayItemViewController
{
    NSLayoutConstraint *_heightConstraint;
    NCDNDViewController *_dndViewController;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NCDNDViewController *dndViewController; // @synthesize dndViewController=_dndViewController;
- (void)loadView;

@end

