//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol NCWidgetControllerProtocol
- (void)widgetHasContent:(_Bool)arg1 withIdentifier:(NSString *)arg2;
@end

