//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSCalendar.h>

@interface NSCalendar (NCDateExtensions)
- (long long)yearsWithinEraFromDate:(id)arg1 toDate:(id)arg2;
- (long long)daysWithinEraFromDate:(id)arg1 toDate:(id)arg2;
@end

