//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSUserNotification.h>

@class NSImage, NSString;

@interface NSUserNotification (NCHelpers)
+ (id)keyPathsForValuesAffectingScaledContentImage;
+ (id)keyPathsForValuesAffectingIdentityImage;
@property(readonly, copy, nonatomic) NSString *ncNotificationExtensionIdentifier;
@property(readonly, copy, nonatomic) NSString *ncAlertExtensionIdentifier;
@property(readonly, nonatomic) NSImage *systemAppImage;
- (void)setAlternateActionIndex:(unsigned long long)arg1;
- (void)clearScaledContentImage;
@property(readonly, nonatomic) NSImage *scaledContentImage;
- (void)clearIdentityImage;
@property(readonly, nonatomic) NSImage *identityImage;
@end

