//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSView (imageGeneration)
+ (void)setNCIgnoresWindowChangedNotifications:(BOOL)arg1;
+ (BOOL)ncIgnoresWindowChangedNotifications;
- (id)_renderImageOfContents;
@property(nonatomic) BOOL safeHidden;
@end

