//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "OS_dispatch_source-Protocol.h"

@protocol OS_dispatch_source_data_or <OS_dispatch_source>
@end

