//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 22:31:18).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol WeatherSummaryProtocol
- (void)getWeatherSummaryInCelcius:(BOOL)arg1 withRely:(void (^)(NSString *, unsigned long long))arg2;
@end

